#!/usr/bin/env python3
"""Generate exact-value golden digests for the official ASWF openexr-images corpus.

The corpus itself is too large to check in, so it is downloaded on demand by
testdata/download.sh. What *is* checked in is this manifest of digests, computed
here by reading each image with the OpenEXR reference implementation (through
OpenImageIO's Python bindings). The Go conformance test recomputes the same
digest from its own decode and requires an exact match.

Why a digest of every sample rather than per-channel statistics: min, max and
mean are insensitive to a permutation of the pixels. AllHalfValues.exr decoded
through a broken PIZ path reproduced the reference's min, max, mean, NaN count
and Inf count exactly while nearly every individual pixel was wrong. Summary
statistics are precisely the kind of assertion that looks like verification and
is not.

Digest definition (must match digestChannels in exr/reference_images_test.go):

    for each channel, in EXR sorted (alphabetical) name order:
        write the channel name as UTF-8, then a 0x00 byte
        for each pixel in row-major order:
            write the sample as 4 bytes, little-endian IEEE-754 float32 bits,
            with any NaN replaced by the canonical quiet NaN 0x7FC00000
    SHA-256 over the whole stream

NaN is canonicalised because NaN payload bits are not preserved identically by
every half-to-float conversion, and the payload carries no image meaning.

Usage:  python3.14 scripts/gen-reference-goldens.py   (from the repo root)

Requires the OpenImageIO Python module. On macOS/Homebrew that lives under the
python3.14 site-packages, so run this with python3.14 specifically.
"""

import hashlib
import os
import struct
import sys

try:
    import OpenImageIO as oiio
except ImportError:
    sys.exit(
        "OpenImageIO Python bindings not found.\n"
        "On Homebrew, install openimageio and run this with python3.14."
    )

CORPUS = "testdata/openexr-images"
OUT = "exr/testdata/openexr_images.golden"

CANONICAL_NAN = 0x7FC00000


def digest_image(path):
    inp = oiio.ImageInput.open(path)
    if inp is None:
        raise SystemExit(f"cannot open {path}: {oiio.geterror()}")

    spec = inp.spec()
    names = list(spec.channelnames)

    # Read every channel as float32, matching what the Go test compares.
    pixels = inp.read_image(0, 0, 0, len(names), "float32")
    if pixels is None:
        raise SystemExit(f"cannot read {path}: {inp.geterror()}")
    inp.close()

    flat = pixels.reshape(-1, len(names))

    h = hashlib.sha256()
    for ci in sorted(range(len(names)), key=lambda i: names[i]):
        h.update(names[ci].encode("utf-8") + b"\x00")
        col = flat[:, ci]
        buf = bytearray()
        for v in col.tolist():
            bits = struct.unpack("<I", struct.pack("<f", v))[0]
            # Canonicalise every NaN encoding (exponent all ones, non-zero mantissa).
            if (bits & 0x7F800000) == 0x7F800000 and (bits & 0x007FFFFF) != 0:
                bits = CANONICAL_NAN
            buf += struct.pack("<I", bits)
        h.update(buf)

    return spec.width, spec.height, [names[i] for i in sorted(range(len(names)), key=lambda i: names[i])], h.hexdigest()


def main():
    if not os.path.isdir(CORPUS):
        sys.exit(f"{CORPUS} not found; run testdata/download.sh first")

    files = sorted(f for f in os.listdir(CORPUS) if f.endswith(".exr"))
    if not files:
        sys.exit(f"no .exr files in {CORPUS}; run testdata/download.sh first")

    lines = [
        "# Exact-value digests for the official ASWF openexr-images corpus.",
        "# Generated by scripts/gen-reference-goldens.py from the OpenEXR",
        "# reference implementation. Do not hand-edit.",
        "#",
        "# format: <file> <width> <height> <channels,comma-separated> <sha256>",
    ]
    for name in files:
        path = os.path.join(CORPUS, name)
        w, h, chans, digest = digest_image(path)
        lines.append(f"{name} {w} {h} {','.join(chans)} {digest}")
        print(f"  {name}: {w}x{h} {chans} {digest[:16]}...")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
